In [14]:
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

filepath = "../input/tabular-playground-series-apr-2021/train.csv"
titanic_data = pd.read_csv(filepath)

**Context **



It is a data analysis about passengers by  Titanic by file: train.csv

In [15]:
print(titanic_data.head())

print("Shape:", titanic_data.shape)

print("Describe:")
print(titanic_data.describe())

**Data quality assessment
**

We have a 12 columns with diffeerent parameters: "Survived", "Pclass", "Name", "Sex", "Age" and ex. 

For data quality assessment we have informatiom about missing values.
It is  67866 missing values about Cabin, 4623 missing values about  "Ticket", 3292 missing values about "Age", 250 missing values about "Embarked", 134 missing values about "Fare".

In [16]:
print("Informatiom about missing values")
print(titanic_data.isnull().sum())
print(titanic_data.info())

**Data exploration **

In [17]:
survived = titanic_data[titanic_data["Survived"]==1]
notSurvived = titanic_data[titanic_data["Survived"]==0]

print("Survived: %i (%.1f percent), Not Survived: %i (%.1f percent), Total: %i"\
      %(len(survived), 1.*len(survived)/len(titanic_data)*100.0,\
        len(notSurvived), 1.*len(notSurvived)/len(titanic_data)*100.0, len(titanic_data)))


print(titanic_data["Name"].value_counts().head(10))

survivedSortBySex=titanic_data.groupby(["Sex"]).sum()["Survived"]
print("Survived sorted by sex")
print(survivedSortBySex)



plt.figure(figsize=[16,10])
sns.displot(data=titanic_data, x="Survived")
plt.title("all survival")
plt.xlabel("survival(0 = No, 1 = Yes)")
plt.ylabel("people number")


plt.figure(figsize=[14,10])
sns.barplot(x=titanic_data["Sex"],y=titanic_data["Survived"])
plt.title("survival by sex")


plt.figure(figsize=[16,10])
sns.distplot(survived["Age"].dropna().values,kde=False, color="Green",label="survived")
plt.legend()
sns.distplot(notSurvived["Age"].dropna().values,kde=False, color="Red",label="not survived")
plt.title("survival by age")
plt.legend()
plt.xlabel("age")
plt.ylabel("people number")


plt.figure(figsize=[16,10])
sns.barplot("Embarked", "Survived", data=titanic_data, palette="light:#5A9")
plt.title("survival by embarkation")


plt.figure(figsize=[16,10])
sns.barplot("SibSp", "Survived", data=titanic_data, palette="ch:s=.25,rot=-.25")
plt.title("survival because of siblings / spouses")


plt.figure(figsize=[16,10])
sns.barplot("Parch", "Survived", data=titanic_data, palette="Set2")
plt.title("survival because of parents / children")


sns.set_style("whitegrid")
plt.figure(figsize=[16,10])
sns.barplot("Pclass", "Survived", data=titanic_data, hue="Sex",  palette="pastel")
plt.title("survived people from different ticket class")


ax = plt.subplots(figsize =( 12 , 10 ))
sns.heatmap(titanic_data.drop("PassengerId",axis=1).corr(), vmax=1.0, square=True, annot=True)
plt.title("correlation between parameters")


sns.set_style("whitegrid")
plt.figure(figsize=[16,10])
sns.barplot("Pclass", "Age", data=titanic_data, palette="pastel")
plt.title("correlation between pclass and age")

sns.set_style("whitegrid")
plt.figure(figsize=[16,10])
sns.barplot("Pclass", "Fare", data=titanic_data, palette="pastel")
plt.title("correlation between pclass and fare")

sns.set_style("whitegrid")
plt.figure(figsize=[16,10])
sns.regplot(x="Fare",y="Age", data=titanic_data)
plt.title("correlation between fare and age")

sns.set_style("whitegrid")
plt.figure(figsize=[16,10])
sns.scatterplot(x="Parch",y="SibSp", data=titanic_data)
plt.title("correlation between parch and sibSp")


sns.distplot(survived["Fare"].dropna(), kde=False, color="Green",label="number of survived")
sns.distplot(notSurvived["Fare"].dropna(), kde=False, color="Red",axlabel="Fare",label="not survived")
plt.legend()
plt.title("survival of passengers by fare")

**Summary**

The analysis of data about passagers by Titanic was carried out. Number of PassengerId was 100000. 

Survived: 42774 (42.8 percent), Not Survived: 57226 (57.2 percent). 

Females on the ship was 31226, male 11548 (women were approximately 2.7 times more than men). Also more women then men were survived.

The most popular passagers names are John Johnson, James Smith, John Smith, William Johnson, Michael Smith, William Smith, James Jones, Robert    Smith, James Johnson, Mary Smith.   

At the "Age" chart we can see: The medians are nearly identical. Fewer young people have survived (ages 20-28).

"Embarkation" chart: The higherts survival at the embarkation "C", the lowest at the embarkation "S".

"Survival because of siblings / spouses" chart: Having 2 siblings/spouses on board was the best situation for survival.

"Survival because of parents / children" chart: Having 1 or 5 parents / children on board was the best situation for survival.

"Survived people from different ticket class" chart: The best survival were were on 1 and 2 ticket classes (survival by fermale almost the same, but by male at the 1 ticket class better than 2).

Then I was built heatmap of correlation between parameters and explored the values with the highest correlation.
So,the oldest passagers were at 1 class.
You can see that age increases with fare growing. 
The most people with many siblings / spouses and low fare were not survived.